#############################################################################
# Makefile for building: sender
# Generated by qmake (3.1) (Qt 6.4.3)
# Project:  sender.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile sender.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sender1.0.0
DISTDIR = /home/san3/mystupidcode/sender/.tmp/sender1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt6QuickControls2.so /usr/lib/libQt6Quick.so /usr/lib/libQt6OpenGL.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6QmlModels.so /usr/lib/libQt6Qml.so /usr/lib/libQt6Network.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Filesforsend_class.cpp \
		Network.cpp \
		main.cpp \
		thread_for_network.cpp Filesforsend_qml.cpp \
		DialogWin_qml.cpp \
		main_qml.cpp \
		Settings_win_qml.cpp \
		qmlcache_loader.cpp \
		qrc_qmake_resources_qmlcache.cpp \
		qrc_qmake_qmake_immediate.cpp \
		moc_Filesforsend_class.cpp \
		moc_Network.cpp \
		moc_thread_for_network.cpp
OBJECTS       = Filesforsend_class.o \
		Network.o \
		main.o \
		thread_for_network.o \
		Filesforsend_qml.o \
		DialogWin_qml.o \
		main_qml.o \
		Settings_win_qml.o \
		qmlcache_loader.o \
		qrc_qmake_resources_qmlcache.o \
		qrc_qmake_qmake_immediate.o \
		moc_Filesforsend_class.o \
		moc_Network.o \
		moc_thread_for_network.o
DIST          = DialogWin.qml \
		Filesforsend.qml \
		Settings_win.qml \
		android/AndroidManifest.xml \
		android/build.gradle \
		android/gradle.properties \
		android/gradle/wrapper/gradle-wrapper.jar \
		android/gradle/wrapper/gradle-wrapper.properties \
		android/gradlew \
		android/gradlew.bat \
		android/res/values/libs.xml \
		qtquickcontrols2.conf \
		/usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		sender.pro Filesforsend_class.h \
		Network.h \
		thread_for_network.h Filesforsend_class.cpp \
		Network.cpp \
		main.cpp \
		thread_for_network.cpp
QMAKE_TARGET  = sender
DESTDIR       = 
TARGET        = sender


first: all
####### Build rules

sender:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sender.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		sender.pro \
		qmake_resources_qmlcache.qrc \
		qmake_qmake_immediate.qrc \
		/usr/lib/libQt6QuickControls2.prl \
		/usr/lib/libQt6Quick.prl \
		/usr/lib/libQt6OpenGL.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6QmlModels.prl \
		/usr/lib/libQt6Qml.prl \
		/usr/lib/libQt6Network.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile sender.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_httpserver.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_httpserver_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_repparser.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_statemachine.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/qtquickcompiler.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
sender.pro:
qmake_resources_qmlcache.qrc:
qmake_qmake_immediate.qrc:
/usr/lib/libQt6QuickControls2.prl:
/usr/lib/libQt6Quick.prl:
/usr/lib/libQt6OpenGL.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6QmlModels.prl:
/usr/lib/libQt6Qml.prl:
/usr/lib/libQt6Network.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile sender.pro

qmake_all: FORCE


all: Makefile sender

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Filesforsend.qml DialogWin.qml main.qml Settings_win.qml $(DISTDIR)/
	$(COPY_FILE) --parents qmake_resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents qmake_resources_qmlcache.qrc qmake_qmake_immediate.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Filesforsend_class.h Network.h thread_for_network.h $(DISTDIR)/
	$(COPY_FILE) --parents Filesforsend_class.cpp Network.cpp main.cpp thread_for_network.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_qmlcache_make_all: Filesforsend_qml.cpp DialogWin_qml.cpp main_qml.cpp Settings_win_qml.cpp
compiler_qmlcache_clean:
	-$(DEL_FILE) Filesforsend_qml.cpp DialogWin_qml.cpp main_qml.cpp Settings_win_qml.cpp
Filesforsend_qml.cpp: Filesforsend.qml \
		/usr/lib/qt6/qmlcachegen
	/usr/lib/qt6/qmlcachegen --resource=/home/san3/mystupidcode/sender/qmake_resources.qrc -o Filesforsend_qml.cpp Filesforsend.qml

DialogWin_qml.cpp: DialogWin.qml \
		/usr/lib/qt6/qmlcachegen
	/usr/lib/qt6/qmlcachegen --resource=/home/san3/mystupidcode/sender/qmake_resources.qrc -o DialogWin_qml.cpp DialogWin.qml

main_qml.cpp: main.qml \
		/usr/lib/qt6/qmlcachegen
	/usr/lib/qt6/qmlcachegen --resource=/home/san3/mystupidcode/sender/qmake_resources.qrc -o main_qml.cpp main.qml

Settings_win_qml.cpp: Settings_win.qml \
		/usr/lib/qt6/qmlcachegen
	/usr/lib/qt6/qmlcachegen --resource=/home/san3/mystupidcode/sender/qmake_resources.qrc -o Settings_win_qml.cpp Settings_win.qml

compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
qmlcache_loader.cpp: qmake_resources.qrc /usr/lib/qt6/qmlcachegen
	/usr/lib/qt6/qmlcachegen --resource-file-mapping=/home/san3/mystupidcode/sender/qmake_resources.qrc=/home/san3/mystupidcode/sender/qmake_resources_qmlcache.qrc -o qmlcache_loader.cpp qmake_resources.qrc

compiler_rcc_make_all: qrc_qmake_resources_qmlcache.cpp qrc_qmake_qmake_immediate.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qmake_resources_qmlcache.cpp qrc_qmake_qmake_immediate.cpp
qrc_qmake_resources_qmlcache.cpp: qmake_resources_qmlcache.qrc \
		/usr/lib/qt6/rcc \
		/sender \
		Filesforsend.qml \
		resources.prefix \
		$(EQ) \
		DialogWin.qml \
		main.qml \
		Settings_win.qml
	/usr/lib/qt6/rcc -name qmake_resources_qmlcache qmake_resources_qmlcache.qrc -o qrc_qmake_resources_qmlcache.cpp

qrc_qmake_qmake_immediate.cpp: qmake_qmake_immediate.qrc \
		/usr/lib/qt6/rcc \
		qtquickcontrols2.conf
	/usr/lib/qt6/rcc -name qmake_qmake_immediate qmake_qmake_immediate.qrc -o qrc_qmake_qmake_immediate.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Filesforsend_class.cpp moc_Network.cpp moc_thread_for_network.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Filesforsend_class.cpp moc_Network.cpp moc_thread_for_network.cpp
moc_Filesforsend_class.cpp: Filesforsend_class.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/san3/mystupidcode/sender/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/san3/mystupidcode/sender -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/12.2.1 -I/usr/include/c++/12.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/12.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include-fixed -I/usr/include Filesforsend_class.h -o moc_Filesforsend_class.cpp

moc_Network.cpp: Network.h \
		thread_for_network.h \
		Filesforsend_class.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/san3/mystupidcode/sender/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/san3/mystupidcode/sender -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/12.2.1 -I/usr/include/c++/12.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/12.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include-fixed -I/usr/include Network.h -o moc_Network.cpp

moc_thread_for_network.cpp: thread_for_network.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/san3/mystupidcode/sender/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/san3/mystupidcode/sender -I/usr/include/qt6 -I/usr/include/qt6/QtQuickControls2 -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/12.2.1 -I/usr/include/c++/12.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/12.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include-fixed -I/usr/include thread_for_network.h -o moc_thread_for_network.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_qmlcache_clean compiler_qmlcache_loader_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

Filesforsend_class.o: Filesforsend_class.cpp Filesforsend_class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Filesforsend_class.o Filesforsend_class.cpp

Network.o: Network.cpp Network.h \
		thread_for_network.h \
		Filesforsend_class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Network.o Network.cpp

main.o: main.cpp Network.h \
		thread_for_network.h \
		Filesforsend_class.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

thread_for_network.o: thread_for_network.cpp thread_for_network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread_for_network.o thread_for_network.cpp

Filesforsend_qml.o: Filesforsend_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Filesforsend_qml.o Filesforsend_qml.cpp

DialogWin_qml.o: DialogWin_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DialogWin_qml.o DialogWin_qml.cpp

main_qml.o: main_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_qml.o main_qml.cpp

Settings_win_qml.o: Settings_win_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settings_win_qml.o Settings_win_qml.cpp

qmlcache_loader.o: qmlcache_loader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlcache_loader.o qmlcache_loader.cpp

qrc_qmake_resources_qmlcache.o: qrc_qmake_resources_qmlcache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmake_resources_qmlcache.o qrc_qmake_resources_qmlcache.cpp

qrc_qmake_qmake_immediate.o: qrc_qmake_qmake_immediate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmake_qmake_immediate.o qrc_qmake_qmake_immediate.cpp

moc_Filesforsend_class.o: moc_Filesforsend_class.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Filesforsend_class.o moc_Filesforsend_class.cpp

moc_Network.o: moc_Network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Network.o moc_Network.cpp

moc_thread_for_network.o: moc_thread_for_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thread_for_network.o moc_thread_for_network.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/sender/bin || mkdir -p $(INSTALL_ROOT)/opt/sender/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/sender/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/sender/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/sender/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

